---
- name: tpot_playbook
  hosts: tpot_server1
  become: yes

  tasks:
    #Getting packages
    - name: "Install net-tools"
      apt:
        name: net-tools

    - name: "Install git"
      apt:
        name: git

    #Cloning repos
    - name: Cloning T-Pot install directory
      git:
        repo: "https://github.com/telekom-security/tpotce.git"
        dest: /root/tpot

    - name: Cloning squiDeploy repo
      git:
        repo: "https://github.com/totoaleau/squiDeploy"
        dest: /home/vagrant/squiDeploy

    #TPot install
    - name: Copy T-Pot configuration file
      command: cp /home/vagrant/squiDeploy/TPot/tpot.conf.dist /root/tpot.conf

    - name: Change permissions of tpot config file
      command: chmod 0644 /root/tpot.conf

    - name: Install T-Pot on instance -  be patient, this might take 15 to 30 minutes depending on the connection speed.
      command: /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf

    - name: Delete T-Pot configuration file
      command: rm /root/tpot.conf -f

    - name: Change unattended-upgrades to take default action
      blockinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        block: |
          Dpkg::Options {
            "--force-confdef";
            "--force-confold";
          }

        # Install filebeat
    - name: Ensure required dependencies are present.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present

    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        state: present

    - name: Add Filebeat repository.
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present
        update_cache: true

    - name: install filebeat
      apt:
        name: filebeat

    - name: copying file with playbook
      become: true
      copy:
        src: /home/vagrant/squiDeploy/TPot/filebeat.yml
        dest: /etc/filebeat/
        remote_src: yes
        force: yes

    # Start filebeat service
    - name: Enabling filebeat service
      systemd:
        name: filebeat
        enabled: yes
        daemon_reload: yes

    - name: Starting filebeat service
      systemd:
        name: filebeat
        state: started

    - name: Ensure filebeat is running
      systemd: state=started name=filebeat

    #Reboot
    - name: Finally rebooting T-Pot
      command: shutdown -r now
      async: 1
      poll: 0
