---
- name: tpot1_playbook
  hosts: tpot_server11
  become: yes

  tasks:
    - name: "Hello"
      debug:
        msg: Hello ansible World !

    - name: "Install net-tools"
      apt:
        name: net-tools

    - name: "Install git"
      apt:
        name: git

    - name: Cloning T-Pot install directory
      git:
        repo: "https://github.com/telekom-security/tpotce.git"
        dest: /root/tpot

    - name: Cloning squiDeploy repo
      git:
        repo: "https://github.com/totoaleau/squiDeploy"
        dest: /home/vagrant/squiDeploy

    - name: Copy T-Pot configuration file
      command: cp /root/tpot/iso/installer/tpot.conf.dist /root/tpot.conf

    - name: Change permissions of tpot config file
      command: chmod 0644 /root/tpot.conf

    - name: Install T-Pot on instance -  be patient, this might take 15 to 30 minutes depending on the connection speed.
      command: /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf

    - name: Delete T-Pot configuration file
      command: rm /root/tpot.conf -f

    - name: Change unattended-upgrades to take default action
      blockinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        block: |
          Dpkg::Options {
            "--force-confdef";
            "--force-confold";
          }

        # Install filebeat
    - name: install filebeat
      apt:
        name: filebeat

    - name: copying file with playbook
      become: true
      copy:
        src: /home/vagrant/squiDeploy/TPot/filebeat.yml
        dest: /etc/filebeat/
        remote_src: yes
        force: yes

    # Start filebeat service
    - name: Enabling filebeat service
      systemd:
        name: filebeat
        enabled: yes
        daemon_reload: yes

    - name: Starting filebeat service
      systemd:
        name: filebeat
        state: started

    - name: Ensure filebeat is running
      systemd: state=started name=filebeat

    - name: Finally rebooting T-Pot
      command: shutdown -r now
      async: 1
      poll: 0
